apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - namespace.yaml
  - deployment-v1.yaml
  - deployment-v2.yaml
  - services.yaml
configMapGenerator:
  - name: demo-v1-nginx
    files:
      - nginx.conf=config/v1/nginx.conf
      - index.txt=config/v1/index.txt
    options:
      labels:
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: v1
  - name: demo-v2-nginx
    files:
      - nginx.conf=config/v2/nginx.conf
      - index.txt=config/v2/index.txt
    options:
      labels:
        app.kubernetes.io/name: demo
        app.kubernetes.io/version: v2
